[project]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code Python solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "requests>=2.32.5",
    "z3-solver>=4.15.4.0",
]
